[package]
name = 'aptos_token'
version = '1.0.0'

[dependencies]
AptosFramework = {git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-framework'}
AptosToken = {git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'mainnet', subdir = 'aptos-move/framework/aptos-token'}

[addresses]
source_addr = '0xcafe'
hotboice = '0xcafe'